---
- name: "Prepare steps"
  block:

  - name: "Add Prometheus group"
    ansible.builtin.group:
      name: prometheus
      state: present
      system: true

  - name: "Add Prometheus user"
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      home: "{{ prometheus_db_dir }}"
      createhome: false
      system: true
      shell: "/usr/sbin/nologin"

  - name: "Create config dir"
    ansible.builtin.file:
      path: "{{ prometheus_config_dir }}"
      state: directory
      owner: prometheus
      group: prometheus
      mode: 0755

  - name: "Create data dir"
    ansible.builtin.file:
      path: "{{ prometheus_db_dir }}"
      state: directory
      owner: prometheus
      group: prometheus
      mode: 0755


- name: "Get and install Prometheus"
  block:

  - name: "Get checksum list"
    ansible.builtin.set_fact:
      prometheus_checksums_fact: "{{ lookup('url', prometheus_checksum_url, wantlist=True) | list }}"
    run_once: true
    until: prometheus_checksums_fact is search('linux-' + arch + '.tar.gz')
    retries: 5

  - name: "Get checksum to check target archive"
    ansible.builtin.set_fact:
      prometheus_checksum_fact: "{{ item.split(' ')[0] }}"
    with_items: "{{ prometheus_checksums_fact }}"
    when:
      - "('linux-' + arch + '.tar.gz') in item"

  - name: "Download Prometheus binary"
    become: false
    ansible.builtin.get_url:
      url: "{{ prometheus_url }}"
      dest: "/tmp/{{ prometheus_archive }}"
      mode: 0644
      checksum: "sha256:{{ prometheus_checksum_fact }}"
    retries: 5
    delay: 2
    delegate_to: localhost

  - name: "Unarchive Prometheus"
    become: false
    ansible.builtin.unarchive:
      src: "/tmp/{{ prometheus_archive }}"
      dest: "/tmp/"
    delegate_to: localhost

  - name: "Copy Prometheus and Promtool binaries to server"
    ansible.builtin.copy:
      src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ arch }}/{{ item }}"
      dest: "{{ prometheus_install_dir }}/{{ item }}"
      mode: 0755
      owner: root
      group: root
    with_items:
      - prometheus
      - promtool

  - name: "Copy default console to server"
    ansible.builtin.copy:
      src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ arch }}/{{ item }}"
      dest: "{{ prometheus_config_dir }}/{{ item }}"
      mode: 0755
      owner: root
      group: root
    with_items:
      - consoles
      - console_libraries

  - name: "Copy Prometheus config file to server"
    ansible.builtin.template:
      src: "{{ prometheus_config_file }}"
      dest: "{{ prometheus_config_dir }}/prometheus.yml"
      owner: root
      group: prometheus
      mode: 0640
    notify:
      "reload prometheus"

  - name: "Copy systemd unit"
    ansible.builtin.template:
      src: prometheus.service.j2
      dest: /etc/systemd/system/prometheus.service
      owner: root
      group: root
      mode: 0644
    notify:
      "restart prometheus"

  - name: "Start and enabled Prometheus service"
    ansible.builtin.service:
      daemon_reload: true
      name: prometheus
      state: started
      enabled: true
