---
  - name: "Restart Prometheus"
    ansible.builtin.service:
      daemon_reload: true
      name: prometheus
      state: restarted
    listen: "restart prometheus"

  - name: "Reload Prometheus"
    ansible.builtin.service:
      name: prometheus
      state: reloaded
    listen: "reload prometheus"
